### ISSUE TITLE
hello！我最近在复现JSAC上Automatic Virtual Network Embedding那一篇，但是结果一直不好，如果您已经复现出来了的话，能否分享一下code，我学习一下，thankyou！

### ISSUE THREAD

**Issue by lwz0324** [GeminiLight/virne#1]

**Comment by GeminiLight** [comment]
你可以先尝试将训练轮数尽可能的放大，GNN+RL学习VNE这种比较难的组合优化问题，收敛会很慢，需要收集大量experience

**Comment by Rory0730** [comment]
> _No description provided._

您好！我也在尝试复现这篇GCN+RL的论文，不知道您有没有进展呢？

**Comment by lwz0324** [comment]
> > _No description provided._
> 
> 您好！我也在尝试复现这篇GCN+RL的论文，不知道您有没有进展呢？

之前复现时效果一直不好，后来就放弃了，汗颜。。
