### ISSUE TITLE
nfvdeep那个算法跑不起来

### ISSUE THREAD

**Issue by LayDownToDeath** [GeminiLight/virne#10]
你好，nfvdeep那个算法跑不起来，我跑的版本是当前版本，项目中的算法名称是pg_mlp，能帮忙看看吗,，求求了？

**Comment by LayDownToDeath** [comment]
PgMlpSolver.py没有实现这两个方法learn_with_instance(self, instance)，solve(self, instance)

**Comment by GeminiLight** [comment]
已修复，感谢反馈

**Comment by LayDownToDeath** [comment]
大佬还想问个问题，为什么代码pg_mlp里面没有考虑要嵌入虚拟节点的信息呀，比如所需带宽，cpu这些？

**Comment by GeminiLight** [comment]
可以咨询下相关论文的作者，也欢迎对比我们在ICC 2021的工作 `a3c_gcn_seq2seq` ，它是综合考虑虚拟网络与物理网络的信息的。
