### ISSUE TITLE
In base/counter.py , These equations seem to be wrong 

### ISSUE THREAD

**Issue by chinawang10** [GeminiLight/virne#11]
![image](https://github.com/GeminiLight/virne/assets/59087139/8951e422-bee4-4d4d-82f5-b8b817f68b45)
Here should be division instead of multiplication, right?

**Comment by GeminiLight** [comment]
According to most related papers, the revenue and cost are commonly defined as follows: "Revenue equals the resource request of a VNR multiplied by its lifetime, while cost is calculated by multiplying the resource consumption of the VNR by its lifetime." To further support this claim and provide additional evidence, please allow me a moment to gather some relevant information.
