### ISSUE TITLE
load gml with PhysicalNetwork.load_dataset

### ISSUE THREAD

**Issue by Rorsachach** [GeminiLight/virne#12]
Hello, I want to repeat the experiment in a fixed network, so I need to serialize this network. But I'm running into a little problem. As required in Scenario, I set `save_dir="./dataset/topology/"` in config, and then specified `topology: file_path: './dataset/topology/MultiDomain.gml'`. Then naturally execute the `get_p_net_dataset_dir_from_setting` function at `Scenario.from_config`. But I don't understand why it is necessary to suffix the folder with some information about the cpu size to find the topology subfolder, for example `"'./dataset/topology/MultiDomain-cpu_[50-100]-max_cpu_None-bw_[50-100]-max_bw_None-ltc_[0.0-1.0]'"`. Secondly, when carrying out the code of `load_dataset` or `from_config.try`, there will be a small problem that `self.degree_benchmark` cannot be found. It seems that the setting of `degree_benchmark` is in the `generate_topology` function, but neither of these steps requires `generate_topology`.

**Comment by GeminiLight** [comment]
To assist you better, could you please provide the specific error message related to the program? This will help me understand the problem you are facing more accurately.
