### ISSUE TITLE
Anyone knows what leads to this error when running pgcnn

### ISSUE THREAD

**Issue by Rory0730** [GeminiLight/virne#2]
![image](https://user-images.githubusercontent.com/118961321/203714790-010e6061-b725-4747-ae8f-5f45de6f2e82.png)
in solver/learning/pg_cnn/sub_env:
in concatenate(*args, **kwargs)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

**Comment by GeminiLight** [comment]
Hi, Rory. The inconsistent shape of concatenated arrays may triggers this error. Please check the shape of `norm_node_attrs_data`, `norm_edge_aggr_attrs_data`, `pn_nodes_degree`, 
 and `avg_distance`.

Additionally, a new vision will be released recently, fixing possible errors and adding more functions.

**Comment by GeminiLight** [comment]
> ![image](https://user-images.githubusercontent.com/118961321/203714790-010e6061-b725-4747-ae8f-5f45de6f2e82.png) in solver/learning/pg_cnn/sub_env: in concatenate(*args, **kwargs)
> 
> ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Hi, Rory. The inconsistent shape of concatenated arrays may trigger this error. Please check the shape of norm_node_attrs_data, norm_edge_aggr_attrs_data, pn_nodes_degree,
and avg_distance.

Additionally, a new vision will be released recently, fixing possible errors and adding more functions.



> ![image](https://user-images.githubusercontent.com/118961321/203714790-010e6061-b725-4747-ae8f-5f45de6f2e82.png) in solver/learning/pg_cnn/sub_env: in concatenate(*args, **kwargs)
> 
> ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Hi, Rory. The inconsistent shape of concatenated arrays may trigger this error. Please check the shape of `norm_node_attrs_data`, `norm_edge_aggr_attrs_data`, `pn_nodes_degree`, and `avg_distance`.

Additionally, a new vision will be released recently, fixing possible errors and adding more functions.

**Comment by GeminiLight** [comment]
Hi, Rory. The inconsistent shape of concatenated arrays may trigger this error. Please check the shape of `norm_node_attrs_data`, `norm_edge_aggr_attrs_data`, `pn_nodes_degree`, and `avg_distance`.

Additionally, a new vision will be released recently, fixing possible errors and adding more functions.

**Comment by Rory0730** [comment]
> Hi, Rory. The inconsistent shape of concatenated arrays may trigger this error. Please check the shape of `norm_node_attrs_data`, `norm_edge_aggr_attrs_data`, `pn_nodes_degree`, and `avg_distance`.
> 
> Additionally, a new vision will be released recently, fixing possible errors and adding more functions.

Glad to receive your reply! This error occurs even if uses the default configs, I will check the shape of these arrays further. 
Your work on this project is very rewarding， looking forward to the newest version!!!

**Comment by GeminiLight** [comment]
> > Hi, Rory. The inconsistent shape of concatenated arrays may trigger this error. Please check the shape of `norm_node_attrs_data`, `norm_edge_aggr_attrs_data`, `pn_nodes_degree`, and `avg_distance`.
> > Additionally, a new vision will be released recently, fixing possible errors and adding more functions.
> 
> Glad to receive your reply! This error occurs even if uses the default configs, I will check the shape of these arrays further. Your work on this project is very rewarding， looking forward to the newest version!!!

Hi! The new version has been released, where variable-level, functional-level, and structure-level differences are unavoidable. Welcome to try it, which may avoid the problem you are currently facing. If you are still having trouble, please feel free to let me know.

**Comment by Rory0730** [comment]
I really appreciate it！

**Comment by Rory0730** [comment]
> > > Hi, Rory. The inconsistent shape of concatenated arrays may trigger this error. Please check the shape of `norm_node_attrs_data`, `norm_edge_aggr_attrs_data`, `pn_nodes_degree`, and `avg_distance`.
> > > Additionally, a new vision will be released recently, fixing possible errors and adding more functions.
> > 
> > 
> > Glad to receive your reply! This error occurs even if uses the default configs, I will check the shape of these arrays further. Your work on this project is very rewarding， looking forward to the newest version!!!
> 
> Hi! The new version has been released, where variable-level, functional-level, and structure-level differences are unavoidable. Welcome to try it, which may avoid the problem you are currently facing. If you are still having trouble, please feel free to let me know.

I really appreciate it！
