### ISSUE TITLE
Meta-heuristics Solvers下的算法都不能跑通

### ISSUE THREAD

**Issue by wxe123** [GeminiLight/virne#28]
当我运行sa算法时报错，然后我尝试了ga算法，aco算法也是报错，默认样例里的nrm_rank',算法是能跑通的。
![QQ截图20240202213800](https://github.com/GeminiLight/virne/assets/31402704/9373409b-5727-4a86-8268-d2ec859d5a30)
![QQ截图20240202214201](https://github.com/GeminiLight/virne/assets/31402704/8a040266-b978-45f8-abc2-0f2636832f77)

**Comment by wxe123** [comment]
作者您好，是我运行环境有问题还是代码存在的问题呢

**Comment by GeminiLight** [comment]
Thanks for your feedback. This bug has been fixed by adding the func `update` to `virne.base.solution.Solution`. Feel free to retry the meta-heuristics, and contact me if you have more questions.
