### ISSUE TITLE
gae_vne

### ISSUE THREAD

**Issue by liqunyazhushi** [GeminiLight/virne#3]
i want to learn about gae_vne based on its code, but i can not find it in the repository. really need help, thanks

**Comment by GeminiLight** [comment]
Thanks for your letter. The code for `gae_vne` has been released. However, In my experiments, it's not an efficient approach to the practical VNE problem for the BFS trail-based search.  Its performance advantages over its similar counterpart, `rw_bfs`, are not significant enough to justify the effectiveness of using neural networks in this method. We look forward to your further validation and feedback.
